---
- name: Ensure common dependencies are installed
  hosts: todo

  tasks:
    - name: When Ubuntu ensure dependencies are installed
      block:

        - name: Download and execute k3d installer
          shell: curl -sL https://raw.githubusercontent.com/rancher/k3d/main/install.sh | sudo bash -
          become: yes

        - name: Create the cluster
          shell: k3d cluster create
          become: yes

      when: ( ansible_distribution == 'Ubuntu' )