---
- name: Ensure kubectl is installed
  hosts: todo

  tasks:
    - name: When Ubuntu ensure kubectl is installed
      block:
        - name: Install the kubectl snap package
          snap:
            name: kubectl
            channel: "latest/stable"
            classic: yes
            state: present
          become: yes

      when: ( ansible_distribution == 'Ubuntu' )